config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :accounts, only: [:new, :create, :show]
  resources :categories, only: [:new, :create, :destroy]
  resources :images, only: [:new, :create]
  resources :ideas

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  enum role: [:user, :admin]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_and_belongs_to_many :ideas
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

def new
  @account = Account.new
end

def show
end

def create
  @account = Account.create(account_params)
  if @account.save
    session[:account_id] = @account.id
    redirect_to @account
  else
    render :new
  end
end

private

def account_params
  params.require(:account).permit(:username, :password)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_account

  def current_account
    @current_account ||= Account.find(session[:account_id]) if session[:account_id]
  end
end

app/controllers/categories_controller.rb
class CatergoriesController < ApplicationController
  before filter :admin_only

def index
  @categories = Category.all
end

def new
  @category = Category.new
end

def create
  @category = Category.new(category_params)
  if @category.save
    redirect_to categories_path
  else
  end
end

def destroy
  @category = Category.find(params[:id])
  @category.delete
  redirect_to categories_path
end

private

def category_params
  params.require(:category).permit(:name)
end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
  end

  def show
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to ideas_path
    else
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
  end

  def destroy
  end

private

  def idea_params
    params.require(:idea).permit(:name, :description)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before filter :admin_only

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
    else
    end
  end


private

  def image_params
    params.require(:image).permit(:name, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  @account = Account.find_by(username: params[:session][:username])
  if @account && @account.authenticate(params[:session][:password])
    session[:account_id] = @account.id
    redirect_to @account
  else
  end
end

def destroy
  session.clear
  redirect_to login_path
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/new.html.erb
<h1>Create New Account</h1>

<%= form_for(@account) do |f| %>
<%= f.label "Username" %>
<%= f.text_field :username, placeholder: "Username"  %>

<%= f.label "Password" %>
<%= f.text_field :password, placeholder: "Password"  %>
<%= f.submit "Create Account" %>
<% end %>

app/views/accounts/show.html.erb
<h1>My Ideas</h1>
<%= link_to "New Idea", new_idea_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
<%= category.name %>  <%= link_to "Delete", category_path(category.id), method: :delete %>
<% end %>

app/views/categories/new.html.erb
<h1>Create Category</h1>
<%= form_for @category do |f| %>
<%= f.label "Category" %>
<%= f.text_field :category %>
<%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<h1>My Ideas</h1>

  <% @ideas.each do |idea| %>
  <%= idea.name %> - <%= idea.description %> - <%= idea.category.name %> <%= link_to "Delete Idea", idea_path(idea.id), method: :delete %>
  <% end %>

<%= link_to "Create New Idea", new_idea_path %>

app/views/ideas/new.html.erb
<h1>Create New Idea</h1>
<%= form_for @idea do |f| %>
<%= f.label :name %>
<%= f.text_field :name, placeholder: "Name" %>
<%= f.label :description %>
<%= f.text_field :description, placeholder: "Description" %>
<%= f.label :category_id %>
<%= f.text_field :category_id, placeholder: "Category Id" %>
<%= f.submit %>
<% end %>

app/views/images/new.html.erb
<h1>Create New Image</h1>

<%= form_for @image do |f| %>
<%= f.label "Name" %>
<%= f.text_field :name %>
<%= f.label "URL" %>
<%= f.text_field :url %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_account %>
    <%= current_account.username %>
    <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to IdeaBox</h1>

<%= link_to "Sign Up", new_account_path %>
<%= link_to "Log In", login_path %>